<template>
                <!-- Loading "Spinner" -->
    <div role="status" class="loadingio-spinner-blocks-i1ikxohuay">
      <div class="ldio-k6ckflk9v7l">
        <div style="left: 6px; top: 6px; animation-delay: 0s"></div>
        <div style="left: 70px; top: 6px; animation-delay: 0.125s"></div>
        <div style="left: 134px; top: 6px; animation-delay: 0.25s"></div>
        <div style="left: 6px; top: 70px; animation-delay: 0.875s"></div>
        <div style="left: 134px; top: 70px; animation-delay: 0.375s"></div>
        <div style="left: 6px; top: 134px; animation-delay: 0.75s"></div>
        <div style="left: 70px; top: 134px; animation-delay: 0.625s"></div>
        <div style="left: 134px; top: 134px; animation-delay: 0.5s"></div>
      </div>
    </div>
</template>

<script>

export default {
    name : 'Spinner',
    props: {
        size: {
            default: 'md'
        }
    }
}
</script>

<style scoped>
/* Spinner */
/* Loading spinner */
@keyframes ldio-k6ckflk9v7l {
  0% {
    background: #001f2d;
  }
  12.5% {
    background: #001f2d;
  }
  12.625% {
    background: #008fd4;
  }
  100% {
    background: #008fd4;
  }
}
.ldio-k6ckflk9v7l div {
  position: absolute;
  width: 60px;
  height: 60px;
  background: #008fd4;
  animation: ldio-k6ckflk9v7l 1s linear infinite;
}
.loadingio-spinner-blocks-i1ikxohuay {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-k6ckflk9v7l {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-k6ckflk9v7l div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */  
</style>
