<template>
  <main class="back">
  <!-- <Navigation /> -->
  <navigation />
  <h1>Thank you for booking !</h1>
  <!-- Loading "Spinner" -->
  <div role="status" class="loadingio-spinner-blocks-i1ikxohuay">
    <div class="ldio-k6ckflk9v7l">
      <div style="left: 6px; top: 6px; animation-delay: 0s"></div>
      <div style="left: 70px; top: 6px; animation-delay: 0.125s"></div>
      <div style="left: 134px; top: 6px; animation-delay: 0.25s"></div>
      <div style="left: 6px; top: 70px; animation-delay: 0.875s"></div>
      <div style="left: 134px; top: 70px; animation-delay: 0.375s"></div>
      <div style="left: 6px; top: 134px; animation-delay: 0.75s"></div>
      <div style="left: 70px; top: 134px; animation-delay: 0.625s"></div>
      <div style="left: 134px; top: 134px; animation-delay: 0.5s"></div>
    </div>
  </div>
  <section class="Bc">
    <h2>
      A confirmation and details of your reservation will be sent to your email.
    </h2>
    <br />
    <div class="conf">
      <h2>Reservation details</h2>
      <div v-for="book in booking" :key="book.bookingID" class="book-details">
        <div>
          <div>
            <h3>
              Booking by <b>{{ book.name }}</b>
            </h3>
          </div>
          <div>
            <h4>Contacts:</h4>
            <p>Email: {{ book.email }}</p>
            <p>Phone number: {{ book.phone }}</p>
          </div>
          <div>
            <p>Date: {{ book.date }}</p>
            <p>Time: {{ book.time }}</p>
          </div>
          <p>Party of {{ book.pepSize }}</p>
        </div>
      </div>
    </div>
    <div class="row cont">
      <div class="col"><h3>Our address: 96 kings way, parow, Cape town, 7500</h3>
      <h3>Tabemashou</h3>
<div>
 <h5>Contact details</h5> 
 <p>021 485 7894</p>
 <p>info@tabemashou.com</p>

 <h5>Opening Hours</h5> 
 <p>Mon -> Fri: 6:30am-23:00</p>
 <p>Saturday: 7:00am-23:00</p>
 <p>Sunday: 7:00am-21:00</p>
</div>
      </div>
      <div class="col">
        <div class="mapouter">
          <div class="gmap_canvas">
            <iframe class="gmap_iframe" width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=600&amp;height=350&amp;hl=en&amp;q=96 kings way, parow, Cape town, 7500&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
            ></iframe
            ><a href="https://connectionsgame.org/">Connections</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footerComp />
  </main>
</template>

<script>
import navigation from "@/components/Navbar.vue";
import footerComp from "@/components/Footer.vue";

export default {
  components: {
    navigation,
    footerComp,
  },
  // props: ["id"],
  computed: {
    booking() {
      return this.$store.state.last;
    },
  },
  mounted() {
    this.$store.dispatch("fetchLastBooking");
  },
};
</script>

<style scoped>
.back{
  min-height: 100vh;
  background-color: #044B68;
}
.Bc h2 {
  font-size: 30;
}
.book-details {
  text-align: center;
  padding-top: 0;
  /* padding-right: 20%; */
  justify-content: center;
  font-size: 20px;
}

.cont,
.conf {
  border: 3px solid #000000;
  background-color: #fff;
  width: 80%;
  padding: 0;
  margin: 10%;
}

/* Map */
            .mapouter {
              position: relative;
              text-align: right;
              width: 100%;
              height: 350px;
            }
            .gmap_canvas {
              overflow: hidden;
              background: none !important;
              width: 100%;
              height: 350px;
            }
            .gmap_iframe {
              height: 350px !important;
            }

/* Spinner */
/* Loading spinner */
@keyframes ldio-k6ckflk9v7l {
  0% {
    background: #001f2d;
  }
  12.5% {
    background: #001f2d;
  }
  12.625% {
    background: #008fd4;
  }
  100% {
    background: #008fd4;
  }
}
.ldio-k6ckflk9v7l div {
  position: absolute;
  width: 60px;
  height: 60px;
  background: #008fd4;
  animation: ldio-k6ckflk9v7l 10s linear;
}
.loadingio-spinner-blocks-i1ikxohuay {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-k6ckflk9v7l {
  width: 50%;
  height: 50%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-k6ckflk9v7l div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
