<template>
  <!-- Promo -->
  <!-- Navigation -->
  <div class="products container">
    <h1 class="section-title">Tabemashou</h1>

    <!-- Loading "Spinner" -->
    <div v-if="isLoading" class="loadingio-spinner-blocks-i1ikxohuay">
      <div class="ldio-k6ckflk9v7l">
        <div style="left: 6px; top: 6px; animation-delay: 0s"></div>
        <div style="left: 70px; top: 6px; animation-delay: 0.125s"></div>
        <div style="left: 134px; top: 6px; animation-delay: 0.25s"></div>
        <div style="left: 6px; top: 70px; animation-delay: 0.875s"></div>
        <div style="left: 134px; top: 70px; animation-delay: 0.375s"></div>
        <div style="left: 6px; top: 134px; animation-delay: 0.75s"></div>
        <div style="left: 70px; top: 134px; animation-delay: 0.625s"></div>
        <div style="left: 134px; top: 134px; animation-delay: 0.5s"></div>
      </div>
    </div>
    <!-- Actual menu -->
    <section class="eat"> 
      <h1>Let’s eat | 食べましょう</h1>
      <!-- The display -->
      <!-- Breakfast -->
      <h2>Breakfast</h2>
      <div class="list row">
        <div
          class="col-md-4 menu-card"
          v-for="bre in breakfast"
          :key="bre.prodID"
        >
          <div class="menu-details">
            <h5>{{ bre.prodName }}</h5>
            <p>{{ bre.description }}</p>
            <p>{{ bre.category }}</p>
            <p class="price">R {{ bre.amount }}</p>
          </div>
        </div>
      </div>
      <!-- Appetisers -->
      <h2>Appetisers</h2>
      <div class="list row">
        <div
          class="col-md-4 menu-card"
          v-for="tise in tisers"
          :key="tise.prodID"
        >
          <div class="menu-details">
            <h5>{{ tise.prodName }}</h5>
            <p>{{ tise.description }}</p>
            <p>{{ tise.category }}</p>
            <p class="price">R {{ tise.amount }}</p>
          </div>
        </div>
      </div>
      <!-- Main meal -->
      <h2>Main meal</h2>
      <div class="list row">
        <div
          class="col-md-4 menu-card"
          v-for="main in mains"
          :key="main.prodID"
        >
          <div class="menu-details">
            <h5>{{ main.prodName }}</h5>
            <p>{{ main.description }}</p>
            <p>{{ main.category }}</p>
            <p class="price">R {{ main.amount }}</p>
          </div>
        </div>
      </div>
      <!-- Desserts -->
      <h2>Desserts</h2>
      <div class="list row">
        <div
          class="col-md-4 menu-card"
          v-for="des in desserts"
          :key="des.prodID"
        >
          <div class="menu-details">
            <h5>{{ des.prodName }}</h5>
            <p>{{ des.description }}</p>
            <p>{{ des.category }}</p>
            <p class="price">R {{ des.amount }}</p>
          </div>
        </div>
      </div>
      <br>
    </section>
    <br>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return{
      isLoading: false,
    }
  },
  computed: {
    breakfast() {
      return this.$store.state.breakfast;
    },
    tisers() {
      return this.$store.state.tisers;
    },
    mains() {
      return this.$store.state.main;
    },
    desserts() {
      return this.$store.state.dessert;
    },
  },
  mounted() {
    this.$store.dispatch("fetchBreakfast");
    this.$store.dispatch("fetchTisers");
    this.$store.dispatch("fetchMains");
    this.$store.dispatch("fetchDesserts");
  },
};
</script>

<style scoped>
.products{
  background-color: #001f2d ;
  width: 100% !important;
}

.eat {
  background-color: #7BC2F0;
}


/* Spinner */
/* Loading spinner */
@keyframes ldio-k6ckflk9v7l {
  0% {
    background: #001f2d;
  }
  12.5% {
    background: #001f2d;
  }
  12.625% {
    background: #008fd4;
  }
  100% {
    background: #008fd4;
  }
}
.ldio-k6ckflk9v7l div {
  position: absolute;
  width: 60px;
  height: 60px;
  background: #008fd4;
  animation: ldio-k6ckflk9v7l 1s linear infinite;
}
.loadingio-spinner-blocks-i1ikxohuay {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-k6ckflk9v7l {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-k6ckflk9v7l div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
